name: "Hadolint Github Action"
description: "A stable, well-tested, highly configurable way of checking your Dockerfile(s) with Hadolint"
author: "Johan Bergström <bugs@bergstroem.nu>"

inputs:
  dockerfile:
    description: Path to Dockerfile(s). Accepts shell expansions (`**/Dockerfile`)
    required: true
    default: "./Dockerfile"
  config_file:
    description: Path to optional config (hadolint defaults to read `./hadolint.yml` if it exists)
    required: false
    default:
  error_level:
    description: "Fail CI based on hadolint output (`-1`: never, `0`: error, `1`: warning, `2`: info)"
    required: false
    default: 0
  annotate:
    description: Annotate code inline in the github PR viewer (`true`/`false`)
    required: true
    default: true
  output_format:
    description: Set output format (choose between `tty`, `json`, `checkstyle`, `codeclimate` or `gitlab_codeclimate`)
    required: false
    default:
  hadolint_path:
    description: Absolute path to hadolint binary. If unset, it is assumed to exist in `$PATH`
    required: false
    default:

outputs:
  hadolint_output:
    description: Optional output from Hadolint, controlled with `output_format`
  hadolint_version:
    description: Hadolint version

runs:
  using: composite
  steps:
    - name: Download hadolint and make available in path
      shell: bash
      run: |
        VERSION=$(<${{ github.action_path }}/HADOLINT_VERSION)
        mkdir ${{ github.action_path }}/bin
        curl -s -L -o ${{ github.action_path }}/bin/hadolint "https://github.com/hadolint/hadolint/releases/download/v${VERSION}/hadolint-Linux-x86_64"
        chmod +x ${{ github.action_path }}/bin/hadolint
        echo "${{ github.action_path }}/bin" >> $GITHUB_PATH
    - name: Run hadolint.sh
      shell: bash
      env:
        dockerfile: ${{ inputs.dockerfile }}
        config_file: ${{ inputs.config_file }}
        error_level: ${{ inputs.error_level }}
        annotate: ${{ inputs.annotate }}
        output_format: ${{ inputs.output_format }}
      run: ${{ github.action_path }}/hadolint.sh

branding:
  icon: "check"
  color: "green"
