name: lint
on: pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    name: shellcheck
    env:
      SHELLCHECK_VERSION: 0.7.2
    steps:
      - uses: actions/checkout@v2
      - name: install shellcheck
        run: |
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v${{ env.SHELLCHECK_VERSION }}/shellcheck-v${{ env.SHELLCHECK_VERSION }}.linux.x86_64.tar.xz" | tar -xJ
          sudo cp "shellcheck-v${{ env.SHELLCHECK_VERSION }}/shellcheck" /usr/local/bin/
      - name: verify shell scripts
        run: shellcheck hadolint.sh lib/*.sh test/*.sh
  prettier:
    runs-on: ubuntu-20.04
    name: prettier
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14.x"
      - name: install prettier
        run: npm install -g prettier
      - name: run prettier
        run: prettier -c .
