name: lint
on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    name: shellcheck
    env:
      SHELLCHECK_VERSION: 0.7.2
    steps:
      - uses: actions/checkout@v2.3.4
      - name: install shellcheck
        run: |
          wget -q -O - "https://github.com/koalaman/shellcheck/releases/download/v${{ env.SHELLCHECK_VERSION }}/shellcheck-v${{ env.SHELLCHECK_VERSION }}.linux.x86_64.tar.xz" | tar -x -J --strip-components=1 -C . shellcheck-v${{ env.SHELLCHECK_VERSION }}/shellcheck && \
          sudo mv shellcheck /usr/local/bin/
      - name: verify shell scripts
        # shellcheck source path is assumed to be the "root" git directory
        run: shellcheck hadolint.sh lib/*.sh test/*.sh
