name: Lint
on:
  pull_request:
    paths:
      # actionlint
      - ".github/workflows/*.yml"
      # prettier
      - "**.md"
      - "**.yml"
      - "**.json"
      # shellcheck & shfmt
      - "**.sh"

jobs:
  validate-renovate-config:
    name: Validate renovate config
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: validate
        uses: rinchsan/renovate-config-validator@v0.0.12
        with:
          pattern: ".github/renovate.json"
  actionlint:
    name: Actionlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install Actionlint
        env:
          version: "1.6.22"
        run: curl -Ls "https://github.com/rhysd/actionlint/releases/download/v${{ env.version }}/actionlint_${{ env.version }}_linux_amd64.tar.gz" | sudo tar -x -z -C /usr/local/bin actionlint
      - name: Run Actionlint
        run: |
          echo "::add-matcher::.github/matcher-actionlint.json"
          actionlint -color
  prettier:
    runs-on: ubuntu-22.04
    name: Prettier
    steps:
      - uses: actions/checkout@v3.2.0
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "18.11.0"
      - name: Install prettier
        run: npm install -g prettier
      - name: Run prettier
        run: prettier -c .
  shellcheck:
    runs-on: ubuntu-22.04
    name: Shellcheck
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install Shellcheck
        env:
          version: "0.9.0"
        run: curl -Ls "https://github.com/koalaman/shellcheck/releases/download/v${{ env.version }}/shellcheck-v${{ env.version }}.linux.x86_64.tar.xz" | sudo tar -x -J --wildcards --strip-components=1 -C /usr/local/bin "shellcheck*/shellcheck"
      - name: Verify shell scripts
        run: |
          echo "::add-matcher::.github/matcher-shellcheck.json"
          shellcheck -f gcc -S warning hadolint.sh lib/*.sh test/*.sh
  shfmt:
    name: Shfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install shfmt
        env:
          version: "3.6.0"
        run: curl -Ls -o shfmt "https://github.com/mvdan/sh/releases/download/v${{ env.version }}/shfmt_v${{ env.version }}_linux_amd64" && chmod +x shfmt && sudo mv shfmt /usr/local/bin
      - name: Lint shell scripts
        run: shfmt -i 2 -d hadolint.sh lib/*.sh test/*.sh
