name: lint
on:
  pull_request:
    paths:
      - "**.sh"
      - .github/workflows/lint-shfmt.yml

jobs:
  shfmt:
    runs-on: ubuntu-22.04
    name: shfmt
    env:
      SHFMT_VERSION: 3.5.1
    steps:
      - uses: actions/checkout@v3.0.2
      - name: install shfmt
        run: |
          wget -q -O shfmt "https://github.com/mvdan/sh/releases/download/v${{ env.SHFMT_VERSION }}/shfmt_v${{ env.SHFMT_VERSION }}_linux_amd64" && \
          chmod +x shfmt && \
          sudo mv shfmt /usr/local/bin/
      - name: lint shell scripts
        run: shfmt -i 2 -d hadolint.sh lib/*.sh test/*.sh
