name: lint
on: pull_request

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    name: shellcheck
    env:
      SHELLCHECK_VERSION: 0.7.2
    steps:
      - uses: actions/checkout@v2.3.4
      - name: install shellcheck
        run: |
          wget -q -O - "https://github.com/koalaman/shellcheck/releases/download/v${{ env.SHELLCHECK_VERSION }}/shellcheck-v${{ env.SHELLCHECK_VERSION }}.linux.x86_64.tar.xz" | tar -x -J --strip-components=1 -C . shellcheck-v${{ env.SHELLCHECK_VERSION }}/shellcheck && \
          sudo mv shellcheck /usr/local/bin/
      - name: verify shell scripts
        # shellcheck source path is assumed to be the "root" git directory
        run: shellcheck hadolint.sh lib/*.sh test/*.sh
  shfmt:
    runs-on: ubuntu-20.04
    name: shfmt
    env:
      SHFMT_VERSION: 3.3.1
    steps:
      - uses: actions/checkout@v2.3.4
      - name: install shfmt
        run: |
          wget -q -O shfmt "https://github.com/mvdan/sh/releases/download/v${{ env.SHFMT_VERSION }}/shfmt_v${{ env.SHFMT_VERSION }}_linux_amd64" && \
          chmod +x shfmt && \
          sudo mv shfmt /usr/local/bin/
      - name: lint shell scripts
        run: shfmt -i 2 -d hadolint.sh lib/*.sh test/*.sh
  prettier:
    runs-on: ubuntu-20.04
    name: prettier
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: "14.x"
      - name: install prettier
        run: npm install -g prettier
      - name: run prettier
        run: prettier -c .
