name: lint
on:
  pull_request:
    paths:
      # actionlint
      - ".github/workflows/*.yml"
      # prettier
      - "**.md"
      - "**.yml"
      # shellcheck & shfmt
      - "**.sh"

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Install Actionlint
        env:
          ACTIONLINT_VERSION: 1.6.18
        run: |
          wget -q -O- "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_linux_amd64.tar.gz" | tar -x -z -C . actionlint && \
          mv actionlint /usr/local/bin
      - name: Run Actionlint
        run: |
          actionlint -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}{{end}}' -ignore 'SC2016:' .github/workflows/*.yml

  prettier:
    name: prettier
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
      - name: install prettier
        run: npm install -g prettier
      - name: run prettier
        run: prettier -c .
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-22.04
    env:
      SHELLCHECK_VERSION: 0.8.0
    steps:
      - uses: actions/checkout@v3.0.2
      - name: install shellcheck
        run: |
          wget -q -O - "https://github.com/koalaman/shellcheck/releases/download/v${{ env.SHELLCHECK_VERSION }}/shellcheck-v${{ env.SHELLCHECK_VERSION }}.linux.x86_64.tar.xz" | tar -x -J --strip-components=1 -C . shellcheck-v${{ env.SHELLCHECK_VERSION }}/shellcheck && \
          sudo mv shellcheck /usr/local/bin/
      - name: verify shell scripts
        # shellcheck source path is assumed to be the "root" git directory
        run: shellcheck hadolint.sh lib/*.sh test/*.sh
  shfmt:
    name: shfmt
    runs-on: ubuntu-22.04
    env:
      SHFMT_VERSION: 3.5.1
    steps:
      - uses: actions/checkout@v3.0.2
      - name: install shfmt
        run: |
          wget -q -O shfmt "https://github.com/mvdan/sh/releases/download/v${{ env.SHFMT_VERSION }}/shfmt_v${{ env.SHFMT_VERSION }}_linux_amd64" && \
          chmod +x shfmt && \
          sudo mv shfmt /usr/local/bin/
      - name: lint shell scripts
        run: shfmt -i 2 -d hadolint.sh lib/*.sh test/*.sh
