name: test
on:
  push:
    branches:
      - master

jobs:
  hadolint-gh-action:
    name: action
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.1
      - uses: jbergstroem/hadolint-gh-action@master
        with:
          dockerfile: test/fixtures/Dockerfile-valid
