name: test
on: pull_request

jobs:
  bash_unit:
    name: bash_unit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: fetch hadolint version
        run: echo "HADOLINT_VERSION=$(cat HADOLINT_VERSION)" >> "${GITHUB_ENV}"
      - name: install hadolint
        run: |
          wget -q -O hadolint https://github.com/hadolint/hadolint/releases/download/v${{ env.HADOLINT_VERSION }}/hadolint-Linux-x86_64 && \
          chmod +x hadolint && \
          sudo mv hadolint /usr/local/bin/hadolint
      - name: install bash_unit
        env:
          BASH_UNIT_VERSION: 1.7.2
        run: |
          wget -q -O- https://github.com/pgrange/bash_unit/archive/refs/tags/v${{ env.BASH_UNIT_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: output versions
        run: |
          hadolint --version
          bash_unit -v
      - name: run suite
        run: bash_unit test/*.sh
