name: test
on:
  pull_request:

jobs:
  bash_unit:
    name: bash tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: install hadolint
        # yq is like jq for yaml
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#tools
        run: |
          version="$(yq .inputs.version.default action.yml)" && \
          echo "::debug::Downloading Hadolint ${{ env.version }}" && \
          wget -q -O hadolint "https://github.com/hadolint/hadolint/releases/download/v${version}/hadolint-Linux-x86_64" && \
          chmod +x hadolint && \
          sudo mv hadolint /usr/local/bin/hadolint
      - name: install bash_unit
        env:
          BASH_UNIT_VERSION: 2.0.0
        run: |
          wget -q -O- https://github.com/pgrange/bash_unit/archive/refs/tags/v${{ env.BASH_UNIT_VERSION }}.tar.gz | tar xz --strip=1 -C . && \
          sudo mv bash_unit /usr/local/bin
      - name: output versions
        run: |
          hadolint --version
          bash_unit -v
      - name: run suite
        run: bash_unit test/*.sh
  gh-action-default:
    name: action validates dockerfiles
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        with:
          dockerfile: test/fixtures/Dockerfile-valid
  gh-action-version:
    name: action supports custom version
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./
        id: check
        with:
          dockerfile: test/fixtures/Dockerfile-valid
          version: 2.9.0
        env:
          DEBUG: yes
      - name: check hadolint version
        run: |
          if [[ ! "${{ steps.check.outputs.hadolint_version }}" == "2.9.0-no-git" ]]; then
            echo "::error::Version mismatch: \"${{ steps.check.outputs.hadolint_version }}\" does not equal \"2.9.0-no-git\""
            exit 1
          fi
